version: "3"

services:
  DB:
    image: postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
    env_file:
      - docker.env
    ports:
      - "5432:5432"
    networks:
      joasis:
        ipv4_address: 172.1.0.20

  backend:
    depends_on:
      - DB
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "jbackend"
    ports:
      - "8080:8080"
      - "5555:5555"
    env_file:
      - docker.env
    networks:
      joasis:
        ipv4_address: 172.1.0.21

networks:
  joasis:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/24
