version: "3"

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  backend:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_HOST: postgres
      DB_NAME: c23_capstone_gp1
      DB_USER: postgres
      DB_PASS: postgres
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/c23_capstone_gp1?schema=public"
      FRONTEND_URL: http://localhost:3000
