// import { ApplicationStatus, PrismaClient } from "@prisma/client"
import { PrismaClient } from "@prisma/client"
import { hashPassword } from "../utils/hash"

const prisma = new PrismaClient()
enum TagType {
  Performer = "performer",
  Event = "event",
}
// enum Status {
//   completed = "completed",
//   expired = "expired",
//   valid = "valid",
// }

// enum Properties {
//   public = "public",
//   private = "private",
// }
async function main() {
  // await prisma.eventsHashtag.deleteMany()
  // await prisma.performersHashtag.deleteMany()
  // await prisma.hashtagDetail.deleteMany()
  // await prisma.event.deleteMany()
  // await prisma.hashtagDetail.deleteMany()
  // await prisma.client.deleteMany()
  // await prisma.eprofile.deleteMany()
  // await prisma.performer.deleteMany()
  // await prisma.user.deleteMany()

  await prisma.user.createMany({
    data: [
      {
        uuid: "c48df332-662b-499b-a57f-44e9c0fdd6e2",
        username: "ken",
        password: await hashPassword("1234"),
        email: "ken@gmail.com",
        identity: "performer",
        icon: "icon3.jpeg",
        createdAt: new Date("2022-07-11 16:20:48"),
        updatedAt: new Date("2022-08-06 22:46:54"),
      },

      {
        uuid: "56bee6df-80c0-4d80-9c68-fd407f27ba2a",
        username: "maple",
        password: await hashPassword("1234"),
        email: "maple@gmail.com",
        identity: "performer",
        icon: "icon1.jpeg",
        createdAt: new Date("2022-07-11 16:20:48"),
        updatedAt: new Date("2022-08-06 22:46:54"),
      },
      {
        uuid: "e9c678ff-2d43-46c0-a6d2-40e15d3d6192",
        username: "scarlett",
        password: await hashPassword("1234"),
        email: "scarlett@gmail.com",
        identity: "client",
        icon: "icon1.jpeg",
        createdAt: new Date("2022-07-11 16:20:48"),
        updatedAt: new Date("2022-08-06 22:46:54"),
      },

      {
        uuid: "568e9b4c-45f2-4270-ac60-c34fe3468509",
        username: "mei",
        password: await hashPassword("1234"),
        email: "may@gmail.com",
        identity: "client",
        icon: "icon8.jpeg",
        createdAt: new Date("2022-07-11 16:20:48"),
        updatedAt: new Date("2022-08-06 22:46:54"),
      },
      {
        uuid: "54d1e24a-c6a6-4d5b-a23d-a83ae27957a6",
        username: "Jori",
        password: await hashPassword("1234"),
        email: "jismay9@gmail.com",
        identity: "performer",
        icon: "myicon.png",
        createdAt: new Date("2022-07-11 16:20:48"),
        updatedAt: new Date("2022-08-06 22:46:54"),
      },
      {
        uuid: "0b128c89-73c5-437b-90f9-2dfec21b1b83",
        username: "Mauricio",
        password: await hashPassword("1234"),
        email: "mrevillea@gmail.com",
        identity: "performer",
        icon: "icon8.jpeg",
        createdAt: new Date("2022-03-03 18:15:16"),
        updatedAt: new Date("2022-10-26 23:45:55"),
      },
      {
        uuid: "78da2b49-4bdb-411f-ae98-4ddbc8c51c09",
        username: "Dalila",
        password: await hashPassword("1234"),
        email: "dlandreanb@gmail.com",
        identity: "performer",
        icon: "pic.jpeg",
        createdAt: new Date("2022-06-20 08:06:15"),
        updatedAt: new Date("2022-10-23 09:30:43"),
      },
      {
        uuid: "6fb86cba-f4cd-4daa-9c5f-489ecf98be92",
        username: "Madelin",
        password: await hashPassword("1234"),
        email: "masliec@gmail.com",
        identity: "performer",
        icon: "icon8.jpeg",
        createdAt: new Date("2022-05-14 03:26:02"),
        updatedAt: new Date("2022-06-10 21:47:05"),
      },
      {
        uuid: "3e35f414-eeaa-48e2-9348-765c93f77a0c",
        username: "Griffy",
        password: await hashPassword("1234"),
        email: "gsaltmarshed@gmail.com",
        identity: "performer",
        icon: "icon8.jpeg",
        createdAt: new Date("2022-04-14 17:49:25"),
        updatedAt: new Date("2022-12-31 18:47:03"),
      },
      {
        uuid: "608f6e2d-cdb0-462c-8bda-4c6e24986fc2",
        username: "Michel",
        password: await hashPassword("1234"),
        email: "mswyere@gmail.com",
        identity: "performer",
        icon: "icon8.jpeg",
        createdAt: new Date("2022-12-16 00:39:12"),
        updatedAt: new Date("2022-11-24 23:29:18"),
      },
      {
        uuid: "31965474-3787-4175-8da6-b3c9f3544619",
        username: "Reiko",
        password: await hashPassword("1234"),
        email: "rgabrielf@gmail.com",
        identity: "performer",
        icon: "icon2.jpeg",
        createdAt: new Date("2022-09-21 16:42:29"),
        updatedAt: new Date("2022-11-28 05:45:51"),
      },
      {
        uuid: "ac4fa8f7-b6e1-4366-bacb-cf7863eb3b0b",
        username: "Tony",
        password: await hashPassword("1234"),
        email: "ttemplemang@gmail.com",
        identity: "performer",
        icon: "myicon.png",
        createdAt: new Date("2022-01-28 14:02:54"),
        updatedAt: new Date("2022-05-14 01:44:31"),
      },
      {
        uuid: "cf027c56-b1f1-41ed-ac2c-875d42bf9dab",
        username: "Zitella",
        password: await hashPassword("1234"),
        email: "zmanolovh@gmail.com",
        identity: "performer",
        icon: "myicon.png",
        createdAt: new Date("2022-02-16 21:11:43"),
        updatedAt: new Date("2022-04-17 20:56:12"),
      },
      {
        uuid: "99cc397b-333f-4a4e-a4ca-5e3414b4b05e",
        username: "Inez",
        password: await hashPassword("1234"),
        email: "ifrostdykei@gmail.com",
        identity: "performer",
        icon: "icon1.jpeg",
        createdAt: new Date("2022-11-16 00:34:53"),
        updatedAt: new Date("2022-12-23 15:53:18"),
      },
      {
        uuid: "657a3e28-cefc-4b1c-a094-45855fd8c3e5",
        username: "Christian",
        password: await hashPassword("1234"),
        email: "choundsomj@gmail.com",
        identity: "performer",
        icon: "icon8.jpeg",
        createdAt: new Date("2022-10-31 13:24:10"),
        updatedAt: new Date("2022-01-02 03:55:39"),
      },
      {
        uuid: "aa6508cd-7827-4b4b-8d1d-e43ffa50b09b",
        username: "Flore",
        password: await hashPassword("1234"),
        email: "fsaphirk@gmail.com",
        identity: "performer",
        icon: "myicon.png",
        createdAt: new Date("2022-04-06 07:39:14"),
        updatedAt: new Date("2022-12-31 19:12:41"),
      },
      {
        uuid: "32d5dd15-d219-493c-845f-2f7b6d2f3052",
        username: "Lucio",
        password: await hashPassword("1234"),
        email: "lblackboroughl@gmail.com",
        identity: "performer",
        icon: "icon3.jpeg",
        createdAt: new Date("2022-10-24 19:39:47"),
        updatedAt: new Date("2022-04-11 07:28:07"),
      },

      {
        uuid: "da8cb012-3296-4ad8-aff8-0823433ef008",
        username: "Arv",
        password: await hashPassword("1234"),
        email: "aavey34@gmail.com",
        identity: "client",
        icon: "icon1.jpeg",
        createdAt: new Date("2022-09-24 21:13:33"),
        updatedAt: new Date("2022-09-09 22:01:04"),
      },
      {
        uuid: "ba0ef08a-7679-4b7d-93be-8ff97515a19c",
        username: "Yoko",
        password: await hashPassword("1234"),
        email: "ygable35@gmail.com",
        identity: "client",
        icon: "icon1.jpeg",
        createdAt: new Date("2022-02-07 18:56:39"),
        updatedAt: new Date("2022-09-27 17:47:03"),
      },
      {
        uuid: "5383d577-4f19-45bb-815b-0e3ee7ca3e3f",
        username: "Carolyne",
        password: await hashPassword("1234"),
        email: "cfilip36@gmail.com",
        identity: "client",
        icon: "picture.png",
        createdAt: new Date("2022-09-28 07:48:44"),
        updatedAt: new Date("2022-11-25 05:41:30"),
      },
    ],
  })

  ////////////////////////////////////performers (350) start/////////////////////////////////////////////////////

  await prisma.performer.createMany({
    data: [
      {
        users_id: 1,
        years_of_exp: 5,
        birthday: new Date("1997-07-16"),
        contact_number: 93531832,
        contact_email: "performer@gmail.com",
        gender: "male",
        description: "hihihihi! I am ken ",
        facebook_url: null,
        twitter_url: null,
        youtube_url: "www.youtube.com/me",
        ig_url: "www.instagram.com/show",
      },
      {
        users_id: 2,
        years_of_exp: 5,
        birthday: new Date("1998-08-20"),
        contact_number: 93531832,
        contact_email: "performer2@gmail.com",
        gender: "female",
        description: "hihihihi!! I am maple ",
        facebook_url: null,
        twitter_url: null,
        youtube_url: "www.youtube.com/me",
        ig_url: "www.instagram.com/show",
      },
      {
        users_id: 5,
        years_of_exp: 38,
        birthday: new Date("1954-01-16"),
        contact_number: 61547191,
        gender: "female",
        contact_email: "rbelsham4@multiply.com",
        description: "ut nulla sed",
        name: "Reynold Belsham",
        facebook_url: null,
        twitter_url: null,
        youtube_url: "www.youtube.com/me",
        ig_url: "www.instagram.com/show",
        createdAt: new Date("2022-08-19 00:44:29"),
        updatedAt: new Date("2022-11-12 09:37:22"),
      },
      {
        users_id: 6,
        years_of_exp: 34,
        birthday: new Date("1935-10-07"),
        contact_number: 5113590,
        gender: "male",
        contact_email: "sshatliffe5@ucoz.com",
        description: "arcu libero",
        name: "Serge Shatliffe",
        facebook_url: "www.facebook.com/show",
        twitter_url: null,
        youtube_url: "www.youtube.com/user",
        ig_url: "www.instagram.com/me",
        createdAt: new Date("2022-02-19 23:33:51"),
        updatedAt: new Date("2022-06-01 17:42:52"),
      },
      {
        users_id: 7,
        years_of_exp: 18,
        birthday: new Date("1966-04-14"),
        contact_number: 61547191,
        gender: "male",
        contact_email: "rswate6@oakley.com",
        description: "sodales",
        name: "Rasia Swate",
        facebook_url: "www.facebook.com/me",
        twitter_url: null,
        youtube_url: "",
        ig_url: null,
        createdAt: new Date("2022-01-27 21:56:32"),
        updatedAt: new Date("2022-05-21 02:44:31"),
      },
      {
        users_id: 8,
        years_of_exp: 44,
        birthday: new Date("1953-12-22"),
        contact_number: 61547191,
        gender: "female",
        contact_email: "abucknill7@msu.edu",
        description: "leo",
        name: "Alameda Bucknill",
        facebook_url: null,
        twitter_url: null,
        youtube_url: "www.youtube.com/show",
        ig_url: "www.instagram.com/show",
        createdAt: new Date("2022-03-16 05:17:15"),
        updatedAt: new Date("2022-10-12 02:50:43"),
      },
      {
        users_id: 9,
        years_of_exp: 37,
        birthday: new Date("1938-03-14"),
        contact_number: 51135990,
        gender: "male",
        contact_email: "atuke8@goo.gl",
        description: "ultrices phasellus id sapien in",
        name: "Audra Tuke",
        facebook_url: null,
        twitter_url: null,
        youtube_url: null,
        ig_url: "www.instagram.com/perf",
        createdAt: new Date("2022-03-15 13:41:14"),
        updatedAt: new Date("2022-10-07 20:59:24"),
      },
      {
        users_id: 10,
        years_of_exp: 38,
        birthday: new Date("1995-03-27"),
        contact_number: 93531832,
        gender: "other",
        contact_email: "lsore9@360.cn",
        description: "non",
        name: "Lois Sore",
        facebook_url: null,
        twitter_url: null,
        youtube_url: "",
        ig_url: "www.instagram.com/perf",
        createdAt: new Date("2022-10-27 16:14:18"),
        updatedAt: new Date("2022-04-01 18:35:33"),
      },
      {
        users_id: 11,
        years_of_exp: 46,
        birthday: new Date("1950-03-11"),
        contact_number: 93531832,
        gender: "other",
        contact_email: "agrimsteada@tiny.cc",
        description: "mus vivamus vestibulum sagittis sapien",
        name: "Antony Grimstead",
        facebook_url: null,
        twitter_url: null,
        youtube_url: "",
        ig_url: "www.instagram.com/perf",
        createdAt: new Date("2022-01-03 10:58:11"),
        updatedAt: new Date("2022-10-19 13:09:19"),
      },
      {
        users_id: 12,
        years_of_exp: 50,
        birthday: new Date("1989-07-29"),
        contact_number: 93531832,
        gender: "female",
        contact_email: "kmaccarrickb@tumblr.com",
        description: "curabitur in libero ut",
        name: "Katie MacCarrick",
        facebook_url: null,
        twitter_url: null,
        youtube_url: "www.youtube.com/show",
        ig_url: "www.instagram.com/perf",
        createdAt: new Date("2022-11-11 13:45:06"),
        updatedAt: new Date("2022-11-19 15:47:50"),
      },
      {
        users_id: 13,
        years_of_exp: 50,
        birthday: new Date("1981-03-08"),
        contact_number: 51135990,
        gender: "male",
        contact_email: "jleaburnc@yandex.ru",
        description: "nascetur",
        name: "Jolyn Leaburn",
        facebook_url: null,
        twitter_url: null,
        youtube_url: null,
        ig_url: null,
        createdAt: new Date("2022-01-01 06:41:30"),
        updatedAt: new Date("2022-06-12 11:41:30"),
      },
      {
        users_id: 14,
        years_of_exp: 37,
        birthday: new Date("1974-10-16"),
        contact_number: 51135990,
        gender: "female",
        contact_email: "gkinavand@geocities.jp",
        description: "laoreet",
        name: "Gusella Kinavan",
        facebook_url: null,
        twitter_url: null,
        youtube_url: null,
        ig_url: "www.instagram.com/me",
        createdAt: new Date("2022-03-04 17:01:32"),
        updatedAt: new Date("2023-01-20 08:56:04"),
      },
      {
        users_id: 15,
        years_of_exp: 5,
        birthday: new Date("1971-08-17"),
        contact_number: 93591832,
        gender: "male",
        contact_email: "gfainte@businesswire.com",
        description: "suspendisse",
        name: "Glenna Faint",
        facebook_url: null,
        twitter_url: null,
        youtube_url: null,
        ig_url: "www.instagram.com/perf",
        createdAt: new Date("2022-11-07 00:39:45"),
        updatedAt: new Date("2022-11-17 11:25:26"),
      },
      {
        users_id: 16,
        years_of_exp: 27,
        birthday: new Date("1960-10-18"),
        contact_number: 69201945,
        gender: "male",
        contact_email: "bmanoellif@comcast.net",
        description: "consequat morbi a",
        name: "Bridgette Manoelli",
        facebook_url: null,
        twitter_url: null,
        youtube_url: "",
        ig_url: "www.instagram.com/user",
        createdAt: new Date("2022-12-30 10:35:59"),
        updatedAt: new Date("2023-01-06 12:57:33"),
      },
      {
        users_id: 17,
        years_of_exp: 22,
        birthday: new Date("1983-05-10"),
        contact_number: 69201945,
        gender: "male",
        contact_email: "gmacgraghg@sciencedirect.com",
        description: "eget rutrum at lorem integer",
        name: "Gino MacGragh",
        facebook_url: "www.facebook.com/me",
        twitter_url: null,
        youtube_url: "www.youtube.com/me",
        ig_url: "www.instagram.com/perf",
        createdAt: new Date("2022-03-17 17:35:40"),
        updatedAt: new Date("2022-11-25 22:54:50"),
      },
    ],
  })

  ////////////////////////////////////  e_profile (210/350) starts/////////////////////////////////////////////////////////

  const fakeEPorfile = `{
    "header": {
      "iconPosition": "left",
      "iconName": "icon8.jpeg",
      "backgroundImage": "default",
      "colorStyle": "black",
      "displayTab": "about",
      "userName": "Rick Astley",
      "title": "pop dancer",
      "introduction": "Hi I am Rick Astley",
      "contactNumber": "12345678",
      "contactEmail": "RickAstley@email.com"
    },
    "page": [
      {
        "page": 1,
        "pageTitle": "About me",
        "pageName": "SelfIntroducePage",
        "style": "textAndVideo",
        "mainColor": "black",
        "contentsOrMedia": [
          {
            "id": 1,
            "type": "video",
            "content1": "Never Gonna Give You Up",
            "content2": "Hi I am Rick Astley. This is Never Gonna Give You Up (Official Music Video)",
            "content3": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley"
          },
          {
            "id": 2,
            "type": "text",
            "content1": "",
            "content2": "I am an English singer, songwriter and radio personality.",
            "content3": ""
          }
        ]
      },
      {
        "page": 2,
        "pageTitle": "Time Line",
        "pageName": "TimeLinePage",
        "style": "left",
        "mainColor": "black",
        "contentsOrMedia": [
          {
            "id": 1,
            "type": "text",
            "content1": "Signing with Stock Aitken Waterman",
            "content2": "In 1985, Astley was performing as a drummer with a soul band named FBI, with Morris on guitar. They were a well-known local band writing and performing their own music, gigging in pubs and clubs.",
            "content3": ""
          },
          {
            "id": 2,
            "type": "video",
            "content1": "Never Gonna Give You Up",
            "content2": "原唱 at 1987/7/27/",
            "content3": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley"
          },
          {
            "id": 3,
            "type": "image",
            "content1": "Retirement and Return to singing ",
            "content2": "1994 to 2000 was Retirement and in 2000 to present , He was returned to the music industry",
            "content3": "icon2.jpeg"
          },
          {
            "id": 4,
            "type": "video",
            "content1": "Never Gonna Give You Up (粤語)",
            "content2": "粤语改編 at 2021/7/27",
            "content3": "https://www.youtube.com/watch?v=ZhnjLj2Ou90&ab_channel=B%E7%AB%99%E9%95%BF"
          },
          {
            "id": 5,
            "type": "video",
            "content1": "Never Gonna Give You Up (國語)",
            "content2": "國語改編 at 2022/2/19",
            "content3": "https://www.youtube.com/watch?v=vnIGrETLFKg&ab_channel=%E7%B4%94%E6%83%85%E5%B0%8F%E4%B8%AD%E6%9D%91NakamuraC"
          }
        ]
      },
      {
        "page": 3,
        "pageTitle": "Albums",
        "pageName": "AlbumsPage",
        "style": "style1",
        "mainColor": "black",
        "contentsOrMedia": [
          {
            "id": 1,
            "type": "image",
            "content1": "",
            "content2": "",
            "content3": "icon3.jpeg"
          },
          {
            "id": 2,
            "type": "image",
            "content1": "",
            "content2": "",
            "content3": "myicon.png"
          },
          {
            "id": 3,
            "type": "image",
            "content1": "",
            "content2": "",
            "content3": "picture.png"
          },
          {
            "id": 4,
            "type": "image",
            "content1": "",
            "content2": "",
            "content3": "icon2.jpeg"
          }
        ]
      }
    ]
  }`
  await prisma.eprofile.createMany({
    data: [
      {
        performers_id: 1,
        content: fakeEPorfile,
      },
      {
        performers_id: 2,
        content: fakeEPorfile,
      },
      {
        performers_id: 3,
        content: fakeEPorfile,
      },

      {
        performers_id: 4,
        content: fakeEPorfile,
      },
      {
        performers_id: 5,
        content: fakeEPorfile,
      },
      {
        performers_id: 6,
        content: fakeEPorfile,
      },
    ],
  })

  /////////////////////////////////////////////client (650) starts///////////////////////////////////

  await prisma.client.createMany({
    data: [
      {
        users_id: 3,
        name: "scarlett",
        contact_number: 69201945,
        client_type: "individual",
      },
      {
        users_id: 4,
        name: "May Co.",
        contact_number: 69201945,
        client_type: "corporate",
        business_address: "811231 Clemons Terrace",
        business_BR_no: "012378097",
        business_website_url: "www.company.com",
      },
      {
        users_id: 18,
        name: "Twitterwire",
        gender: "other",
        contact_number: 69201945,
        description:
          "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
        contact_email: "kmaclureh@newsvine.com",
        client_type: "corporate",
        business_address: "8171 Clemons Terrace",
        business_BR_no: "0875570097",
        business_website_url: "www.company.com",
        createdAt: new Date("2022-03-21 03:36:25"),
        updatedAt: new Date("2022-08-05 14:02:22"),
      },
      {
        users_id: 19,
        name: "Bubblebox",
        gender: "other",
        contact_number: 51135990,
        description:
          "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
        contact_email: "dvarleyi@ovh.net",
        client_type: "corporate",
        business_address: "189 Mccormick Road",
        business_BR_no: "0638944120",
        business_website_url: "www.recuritment.hk",
        createdAt: new Date("2022-09-12 11:58:07"),
        updatedAt: new Date("2022-09-24 22:39:36"),
      },
      {
        users_id: 20,
        name: "Vipe",
        gender: "other",
        contact_number: 61547191,
        description:
          "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
        contact_email: "mbroadfieldj@china.com.cn",
        client_type: "corporate",
        business_address: "188 Rowland Street",
        business_BR_no: "2646894465",
        business_website_url: "www.recuritment.com",
        createdAt: new Date("2022-05-16 10:23:06"),
        updatedAt: new Date("2022-10-24 13:50:05"),
      },
    ],
  })

  ///////////////////////////////hashtagDetail (perf: 24; event: 11) starts/////////////////////////////////////////////////

  await prisma.hashtagDetail.createMany({
    data: [
      {
        name: "Singer",
        tag_type: TagType.Performer,
      },
      {
        name: "DJ",
        tag_type: TagType.Performer,
      },
      {
        name: "Musician",
        tag_type: TagType.Performer,
      },
      {
        name: "Juggling",
        tag_type: TagType.Performer,
      },
      {
        name: "Dancer",
        tag_type: TagType.Performer,
      },
      {
        name: "Mime",
        tag_type: TagType.Performer,
      },
      {
        name: "Emcee(MC)",
        tag_type: TagType.Performer,
      },
      {
        name: "Comedian",
        tag_type: TagType.Performer,
      },
      {
        name: "Clowning",
        tag_type: TagType.Performer,
      },
      {
        name: "Fire Dancer",
        tag_type: TagType.Performer,
      },
      {
        name: "Fire Breather",
        tag_type: TagType.Performer,
      },
      {
        name: "Aerial and Acrobatic Performer",
        tag_type: TagType.Performer,
      },
      {
        name: "Burlesque",
        tag_type: TagType.Performer,
      },
      {
        name: "Drawer",
        tag_type: TagType.Performer,
      },
      {
        name: "Balloon Twister",
        tag_type: TagType.Performer,
      },
      {
        name: "Performance Artist",
        tag_type: TagType.Performer,
      },
      {
        name: "Sketchers",
        tag_type: TagType.Performer,
      },
      {
        name: "Graffiti Artist",
        tag_type: TagType.Performer,
      },
      {
        name: "Acapello",
        tag_type: TagType.Performer,
      },
      {
        name: "Beatboxer",
        tag_type: TagType.Performer,
      },
      {
        name: "Puppetry",
        tag_type: TagType.Performer,
      },
      {
        name: "Rapper",
        tag_type: TagType.Performer,
      },
      {
        name: "Lion Dance",
        tag_type: TagType.Performer,
      },
      {
        name: "Others",
        tag_type: TagType.Performer,
      },
      {
        name: "Charity Event",
        tag_type: TagType.Event,
      },
      {
        name: "Internal Corporate Event",
        tag_type: TagType.Event,
      },
      {
        name: "Annual Dinner",
        tag_type: TagType.Event,
      },
      {
        name: "Concert",
        tag_type: TagType.Event,
      },
      {
        name: "Party",
        tag_type: TagType.Event,
      },
      {
        name: "Carnival",
        tag_type: TagType.Event,
      },
      {
        name: "Wedding",
        tag_type: TagType.Event,
      },
      {
        name: "Celebration",
        tag_type: TagType.Event,
      },
      {
        name: "Luncheon",
        tag_type: TagType.Event,
      },
      {
        name: "Ceremony",
        tag_type: TagType.Event,
      },
      {
        name: "Others",
        tag_type: TagType.Event,
      },
    ],
  })
  ///////////////////////////////////// performersHashtag (701) starts//////////////////////////////////

  const userUuid = await prisma.user.findMany({
    select: {
      uuid: true,
    },
  })

  await prisma.performersHashtag.createMany({
    data: [
      {
        performers_id: 1,
        hashtag_details_id: 11,
      },
      {
        performers_id: 1,
        hashtag_details_id: 9,
      },
      {
        performers_id: 1,
        hashtag_details_id: 18,
      },
      {
        performers_id: 1,
        hashtag_details_id: 6,
      },
      {
        performers_id: 1,
        hashtag_details_id: 21,
      },
      {
        performers_id: 2,
        hashtag_details_id: 10,
      },
      {
        performers_id: 2,
        hashtag_details_id: 2,
      },
      {
        performers_id: 3,
        hashtag_details_id: 5,
      },
      {
        performers_id: 3,
        hashtag_details_id: 21,
      },
      {
        performers_id: 3,
        hashtag_details_id: 18,
      },
      {
        performers_id: 4,
        hashtag_details_id: 15,
      },
      {
        performers_id: 4,
        hashtag_details_id: 19,
      },
      {
        performers_id: 4,
        hashtag_details_id: 2,
      },
      {
        performers_id: 5,
        hashtag_details_id: 5,
      },
      {
        performers_id: 5,
        hashtag_details_id: 20,
      },
      {
        performers_id: 6,
        hashtag_details_id: 10,
      },
      {
        performers_id: 6,
        hashtag_details_id: 7,
      },
      {
        performers_id: 7,
        hashtag_details_id: 14,
      },
      {
        performers_id: 8,
        hashtag_details_id: 1,
      },
      {
        performers_id: 9,
        hashtag_details_id: 12,
      },
      {
        performers_id: 10,
        hashtag_details_id: 21,
      },
      {
        performers_id: 11,
        hashtag_details_id: 20,
      },
      {
        performers_id: 11,
        hashtag_details_id: 18,
      },
      {
        performers_id: 12,
        hashtag_details_id: 13,
      },
      {
        performers_id: 13,
        hashtag_details_id: 6,
      },
      {
        performers_id: 14,
        hashtag_details_id: 22,
      },
      {
        performers_id: 15,
        hashtag_details_id: 14,
      },
      {
        performers_id: 15,
        hashtag_details_id: 17,
      },
    ],
  })

  //////////////////////////////////event (1000) starts////////////////////////////////////////////

  await prisma.event.createMany({
    data: [
      {
        // performers_id: 2,
        clients_id: 1,
        title: "Wedding",
        wage_offer: 8888,
        start_date: new Date("2023-10-10"),
        end_date: new Date("2023-10-10"),
        rehearsal_needed: false,
        start_time: new Date("15:30:00"),
        end_time: new Date("19:30:00"),
        image: "event1.jpeg",
        description: "MC need!!!!! 求婚宴司儀，婚禮司儀!!!",
        location: "CWB",
        status: "valid",
        properties: "public",
        is_shown: true,
        date_published: new Date("2023-3-15"),
      },

      {
        // performers_id: 2,
        clients_id: 1,
        title: "百日宴",
        wage_offer: 8888,
        start_date: new Date("2023-12-12"),
        end_date: new Date("2023-12-12"),
        rehearsal_needed: false,
        start_time: new Date("10:30:00"),
        end_time: new Date("13:30:00"),
        image: "event2.jpeg",
        description: "魔術表演 小朋友魔術!!!",
        location: "TST",
        status: "valid",
        properties: "public",
        is_shown: true,
        date_published: new Date("2023-3-10"),
      },
      {
        // performers_id: 2,
        clients_id: 2,
        title: "生日會",
        wage_offer: 4800,
        start_date: new Date("2023-09-01"),
        end_date: new Date("2023-09-01"),
        rehearsal_needed: false,
        start_time: new Date("12:30:00"),
        end_time: new Date("15:30:00"),
        image: "event3.jpeg",
        description: "音樂、舞蹈及劇場表演",
        location: "YuenLong",
        status: "valid",
        properties: "public",
        is_shown: true,
        date_published: new Date("2023-3-10"),
      },
      {
        // performers_id: 1,
        clients_id: 2,
        title: "Bridal shower",
        wage_offer: 20075,
        start_date: new Date("2022-02-11"),
        end_date: new Date("2022-04-05"),
        rehearsal_needed: false,
        start_time: new Date("19:46"),
        end_time: new Date("9:38"),
        image: "venue2.jpeg",
        description: "Creating the Best. Day. Ever",
        location: "Sha Tin",
        status: "valid",
        properties: "private",
        is_shown: false,
        date_published: new Date("2022-01-04"),
        // createdAt: new Date("2022-09-14 16:08:01"),
        // updatedAt: new Date("2022-10-12 20:02:17"),
      },
      {
        // performers_id: 2,
        clients_id: 2,
        title: "Valentine's day",
        wage_offer: 46224,
        start_date: new Date("2023-08-28"),
        end_date: new Date("2022-04-11"),
        rehearsal_needed: false,
        start_time: new Date("5:59"),
        end_time: new Date("16:19"),
        image: "venue.jpeg",
        description: "Bringing dreams to life.",
        location: "Sha Tin",
        status: "valid",
        properties: "public",
        is_shown: false,
        date_published: new Date("2022-05-24"),
        // createdAt: new Date("2022-03-14 01:56:55"),
        // updatedAt: new Date("2022-08-10 07:50:36"),
      },
      {
        // performers_id: 1,
        clients_id: 2,
        title: "Father's day",
        wage_offer: 13436,
        start_date: new Date("2022-11-07"),
        end_date: new Date("2023-08-20"),
        rehearsal_needed: true,
        start_time: new Date("12:56"),
        end_time: new Date("3:37"),
        image: "venue6.jpeg",
        description: "!performer wanted!",
        location: "Sai Kung",
        status: "expired",
        properties: "private",
        is_shown: true,
        date_published: new Date("2022-07-30"),
        // createdAt: new Date("2022-07-17 22:48:01"),
        // updatedAt: new Date("2022-10-24 23:33:27"),
      },
      {
        // performers_id: 2,
        clients_id: 3,
        title: "Lounge bar singer",
        wage_offer: 34638,
        start_date: new Date("2022-10-10"),
        end_date: new Date("2023-09-20"),
        rehearsal_needed: true,
        start_time: new Date("17:37"),
        end_time: new Date("9:50"),
        image: "venus8.png",
        description: "Creating the Best. Day. Ever",
        location: "Eastern",
        status: "valid",
        properties: "private",
        is_shown: true,
        date_published: new Date("2022-12-17"),
        // createdAt: new Date("2022-12-27 05:14:33"),
        // updatedAt: new Date("2022-04-26 19:12:20"),
      },
      {
        // performers_id: 2,
        clients_id: 3,
        title: "Bridal shower",
        wage_offer: 4231,
        start_date: new Date("2023-04-25"),
        end_date: new Date("2022-12-24"),
        rehearsal_needed: false,
        start_time: new Date("9:35"),
        end_time: new Date("6:31"),
        image: "venue10.png",
        description: "We build your dream around you.",
        location: "Eastern",
        status: "valid",
        properties: "public",
        is_shown: true,
        date_published: new Date("2022-05-07"),
        // createdAt: new Date("2023-01-04 05:46:07"),
        // updatedAt: new Date("2022-08-23 07:03:09"),
      },
      {
        // performers_id: 2,
        clients_id: 2,
        title: "Roadshow",
        wage_offer: 23763,
        start_date: new Date("2023-11-15"),
        end_date: new Date("2022-12-09"),
        rehearsal_needed: true,
        start_time: new Date("16:28"),
        end_time: new Date("1:06"),
        image: "venue3.jpeg",
        description: "Performer needed!!!!",
        location: "Wong Tai Sin",
        status: "accepted",
        properties: "private",
        is_shown: false,
        date_published: new Date("2022-10-03"),
        // createdAt: new Date("2023-01-08 10:02:10"),
        // updatedAt: new Date("2022-05-29 18:43:26"),
      },
      {
        // performers_id: 2,
        clients_id: 3,
        title: "X'mas party",
        wage_offer: 19642,
        start_date: new Date("2023-03-08"),
        end_date: new Date("2023-06-01"),
        rehearsal_needed: false,
        start_time: new Date("1:50"),
        end_time: new Date("12:19"),
        image: "venue5.jpeg",
        description: "Creating the Best. Day. Ever",
        location: "Kwun Tong",
        status: "expired",
        properties: "private",
        is_shown: false,
        date_published: new Date("2022-01-20"),
        // createdAt: new Date("2022-10-20 04:00:13"),
        // updatedAt: new Date("2022-03-25 20:06:01"),
      },
      {
        clients_id: 3,
        title: "Bar & Solicitor Admission",
        wage_offer: 10252,
        start_date: new Date("2023-12-25"),
        end_date: new Date("2023-07-26"),
        rehearsal_needed: false,
        start_time: new Date("3:59"),
        end_time: new Date("0:12"),
        image: "venue7.jpeg",
        description: "Performer needed!!!!",
        location: "Southern",
        status: "completed",
        properties: "private",
        is_shown: false,
        date_published: new Date("2022-09-09"),
        // createdAt: new Date("2022-08-11 15:46:25"),
        // updatedAt: new Date("2022-07-22 13:06:48"),
      },
      {
        clients_id: 4,
        title: "Graduation",
        wage_offer: 7274,
        start_date: new Date("2023-03-12"),
        end_date: new Date("2023-08-29"),
        rehearsal_needed: true,
        start_time: new Date("23:42"),
        end_time: new Date("6:09"),
        image: "venue3.jpeg",
        description: "Creating the Best. Day. Ever",
        location: "Islands",
        status: "accepted",
        properties: "private",
        is_shown: true,
        date_published: new Date("2022-10-20"),
        // createdAt: new Date("2022-06-22 12:38:40"),
        // updatedAt: new Date("2022-02-27 20:01:01"),
      },
      {
        clients_id: 4,
        title: "Passing Out",
        wage_offer: 4976,
        start_date: new Date("2022-07-04"),
        end_date: new Date("2022-08-14"),
        rehearsal_needed: false,
        start_time: new Date("13:25"),
        end_time: new Date("10:48"),
        image: "venue5.jpeg",
        description: "Bringing dreams to life.",
        location: "Kwai Tsing",
        status: "completed",
        properties: "private",
        is_shown: false,
        date_published: new Date("2023-01-26"),
        // createdAt: new Date("2022-04-24 13:31:11"),
        // updatedAt: new Date("2022-02-11 17:07:06"),
      },
      {
        clients_id: 4,
        title: "Farewell",
        wage_offer: 18125,
        start_date: new Date("2023-09-20"),
        end_date: new Date("2023-02-14"),
        rehearsal_needed: true,
        start_time: new Date("23:33"),
        end_time: new Date("3:16"),
        image: "venue7.jpeg",
        description: "We build your dream around you.",
        location: "Kwun Tong",
        status: "accepted",
        properties: "private",
        is_shown: true,
        date_published: new Date("2022-01-07"),
        // createdAt: new Date("2022-03-16 05:20:31"),
        // updatedAt: new Date("2022-02-19 23:52:22"),
      },
      {
        clients_id: 5,
        title: "Father's day",
        wage_offer: 26204,
        start_date: new Date("2023-10-28"),
        end_date: new Date("2022-12-31"),
        rehearsal_needed: true,
        start_time: new Date("20:10"),
        end_time: new Date("17:52"),
        image: "venue3.jpeg",
        description: "Get the vibe!!!!",
        location: "Kowloon City",
        status: "expired",
        properties: "public",
        is_shown: false,
        date_published: new Date("2022-07-23"),
        // createdAt: new Date("2023-01-04 03:31:23"),
        // updatedAt: new Date("2023-01-21 15:30:17"),
      },
      {
        clients_id: 5,
        title: "Grand opening",
        wage_offer: 7652,
        start_date: new Date("2022-07-25"),
        end_date: new Date("2023-04-02"),
        rehearsal_needed: true,
        start_time: new Date("11:51"),
        end_time: new Date("7:24"),
        image: "venus8.png",
        description: "Bringing dreams to life.",
        location: "Tuen Mun",
        status: "accepted",
        properties: "private",
        is_shown: false,
        date_published: new Date("2022-01-07"),
        // createdAt: new Date("2022-01-15 12:01:35"),
        // updatedAt: new Date("2022-12-30 07:24:40"),
      },
      {
        clients_id: 1,
        title: "Grand opening",
        wage_offer: 34768,
        start_date: new Date("2023-03-12"),
        end_date: new Date("2023-04-13"),
        rehearsal_needed: true,
        start_time: new Date("6:11"),
        end_time: new Date("21:14"),
        image: "venue10.png",
        description: "Creating the Best. Day. Ever",
        location: "Tuen Mun",
        status: "expired",
        properties: "private",
        is_shown: true,
        date_published: new Date("2022-07-13"),
        // createdAt: new Date("2023-01-25 21:17:29"),
        // updatedAt: new Date("2022-12-07 09:58:38"),
      },
      {
        clients_id: 4,
        title: "DJ",
        wage_offer: 3443,
        start_date: new Date("2023-11-13"),
        end_date: new Date("2022-03-19"),
        rehearsal_needed: true,
        start_time: new Date("5:54"),
        end_time: new Date("9:37"),
        image: "venue.jpeg",
        description: "Show must go on!",
        location: "Wan Chai",
        status: "valid",
        properties: "private",
        is_shown: false,
        date_published: new Date("2022-08-15"),
        // createdAt: new Date("2022-03-02 17:46:12"),
        // updatedAt: new Date("2022-01-24 12:36:40"),
      },
      {
        clients_id: 5,
        title: "Graduation",
        wage_offer: 7500,
        start_date: new Date("2022-07-31"),
        end_date: new Date("2022-11-27"),
        rehearsal_needed: true,
        start_time: new Date("0:13"),
        end_time: new Date("5:23"),
        image: "venue10.png",
        description: "We build your dream around you.",
        location: "Southern",
        status: "valid",
        properties: "public",
        is_shown: false,
        date_published: new Date("2022-12-09"),
        // createdAt: new Date("2022-08-29 16:00:28"),
        // updatedAt: new Date("2023-01-22 15:05:46"),
      },
      {
        clients_id: 3,
        title: "Roadshow",
        wage_offer: 10701,
        start_date: new Date("2022-11-29"),
        end_date: new Date("2023-08-04"),
        rehearsal_needed: true,
        start_time: new Date("6:33"),
        end_time: new Date("20:46"),
        image: "venue10.png",
        description: "We build your dream around you.",
        location: "Wong Tai Sin",
        status: "expired",
        properties: "private",
        is_shown: false,
        date_published: new Date("2022-07-16"),
        // createdAt: new Date("2022-06-04 14:56:09"),
        // updatedAt: new Date("2022-09-29 19:57:13"),
      },
      {
        clients_id: 5,
        title: "Birthday",
        wage_offer: 16070,
        start_date: new Date("2022-12-09"),
        end_date: new Date("2022-08-31"),
        rehearsal_needed: false,
        start_time: new Date("15:32"),
        end_time: new Date("9:01"),
        image: "venus8.png",
        description: "Performer needed!!!!",
        location: "Kowloon City",
        status: "valid",
        properties: "private",
        is_shown: true,
        date_published: new Date("2022-01-16"),
        // createdAt: new Date("2022-06-10 07:40:18"),
        // updatedAt: new Date("2022-11-07 19:14:33"),
      },
      {
        clients_id: 4,
        title: "Father's day",
        wage_offer: 45210,
        start_date: new Date("2023-05-18"),
        end_date: new Date("2022-11-29"),
        rehearsal_needed: false,
        start_time: new Date("23:07"),
        end_time: new Date("22:16"),
        image: "venue3.jpeg.venue4.jpeg",
        description: "Show must go on!",
        location: "Kowloon City",
        status: "completed",
        properties: "public",
        is_shown: true,
        date_published: new Date("2022-01-04"),
        // createdAt: new Date("2022-09-18 08:50:45"),
        // updatedAt: new Date("2022-09-14 00:05:22"),
      },
      {
        clients_id: 2,
        title: "Bar & Solicitor Admission",
        wage_offer: 43286,
        start_date: new Date("2023-06-15"),
        end_date: new Date("2023-08-25"),
        rehearsal_needed: false,
        start_time: new Date("7:25"),
        end_time: new Date("13:43"),
        image: "venue6.jpeg",
        description: "Creating the Best. Day. Ever",
        location: "Tsuen Wan",
        status: "valid",
        properties: "public",
        is_shown: true,
        date_published: new Date("2022-10-29"),
        // createdAt: new Date("2022-01-24 07:12:08"),
        // updatedAt: new Date("2022-09-01 10:40:15"),
      },
      {
        clients_id: 1,
        title: "Roadshow",
        wage_offer: 45545,
        start_date: new Date("2023-11-13"),
        end_date: new Date("2022-05-29"),
        rehearsal_needed: false,
        start_time: new Date("0:15"),
        end_time: new Date("8:38"),
        image: "venue9.png",
        description: "Get the vibe!!!!",
        location: "Sha Tin",
        status: "valid",
        properties: "public",
        is_shown: true,
        date_published: new Date("2022-06-28"),
        // createdAt: new Date("2022-10-04 14:33:34"),
        // updatedAt: new Date("2022-02-10 10:38:04"),
      },
      {
        clients_id: 1,
        title: "Proposal",
        wage_offer: 21868,
        start_date: new Date("2023-02-18"),
        end_date: new Date("2022-11-11"),
        rehearsal_needed: false,
        start_time: new Date("10:08"),
        end_time: new Date("0:11"),
        image: "venue3.jpeg.venue4.jpeg",
        description: "Show must go on!",
        location: "Central and Western",
        status: "valid",
        properties: "private",
        is_shown: false,
        date_published: new Date("2022-10-28"),
        // createdAt: new Date("2022-03-25 17:52:24"),
        // updatedAt: new Date("2023-01-17 02:23:13"),
      },
    ],
  })

  //////////////////////// events_application (700) starts///////////////////////////////////

  await prisma.eventsApplication.createMany({
    data: [
      {
        events_id: 1,
        performers_id: 1,
        status: "pending",
        // createdAt: new Date("2022-07-31 21:24:21"),
        // updatedAt: new Date("2022-11-14 00:10:07"),
      },
      {
        events_id: 1,
        performers_id: 2,
        status: "pending",
        // createdAt: new Date("2022-09-24 07:34:36"),
        // updatedAt: new Date("2022-12-12 15:38:04"),
      },
      {
        events_id: 2,
        performers_id: 1,
        status: "pending",
        // createdAt: new Date("2022-11-04 02:43:02"),
        // updatedAt: new Date("2022-11-29 11:52:45"),
      },
      {
        events_id: 2,
        performers_id: 2,
        status: "pending",
        // createdAt: new Date("2022-11-15 08:31:55"),
        // updatedAt: new Date("2022-01-11 19:50:26"),
      },
      {
        events_id: 2,
        performers_id: 3,
        status: "pending",
        // createdAt: new Date("2022-10-02 18:09:45"),
        // updatedAt: new Date("2022-07-02 11:38:45"),
      },
      {
        events_id: 2,
        performers_id: 5,
        status: "pending",
        // createdAt: new Date("2022-03-24 12:15:53"),
        // updatedAt: new Date("2022-07-10 21:41:59"),
      },
      {
        events_id: 3,
        performers_id: 1,
        status: "pending",
        // createdAt: new Date("2022-04-20 05:14:07"),
        // updatedAt: new Date("2022-04-14 22:17:40"),
      },
      {
        events_id: 3,
        performers_id: 2,
        status: "pending",
        // createdAt: new Date("2022-01-25 05:21:00"),
        // updatedAt: new Date("2022-09-04 22:36:18"),
      },
      {
        events_id: 3,
        performers_id: 3,
        status: "pending",
        // createdAt: new Date("2022-09-14 11:32:52"),
        // updatedAt: new Date("2022-05-11 07:46:19"),
      },
      {
        events_id: 3,
        performers_id: 4,
        status: "pending",
        // createdAt: new Date("2022-05-29 06:20:01"),
        // updatedAt: new Date("2022-01-04 04:40:02"),
      },
      {
        events_id: 3,
        performers_id: 5,
        status: "pending",
        // createdAt: new Date("2023-01-18 18:07:29"),
        // updatedAt: new Date("2023-01-15 15:27:37"),
      },
      {
        events_id: 4,
        performers_id: 1,
        status: "pending",
        // createdAt: new Date("2023-01-12 18:28:47"),
        // updatedAt: new Date("2022-02-17 18:20:24"),
      },
      {
        events_id: 4,
        performers_id: 2,
        status: "pending",
        // createdAt: new Date("2022-09-03 02:31:29"),
        // updatedAt: new Date("2022-10-31 10:14:55"),
      },
      {
        events_id: 4,
        performers_id: 3,
        status: "pending",
        // createdAt: new Date("2023-01-23 06:44:45"),
        // updatedAt: new Date("2022-08-22 15:08:08"),
      },
      {
        events_id: 4,
        performers_id: 4,
        status: "reject",
        // createdAt: new Date("2022-08-08 17:54:31"),
        // updatedAt: new Date("2022-04-15 09:20:17"),
      },
      {
        events_id: 4,
        performers_id: 5,
        status: "pending",
        // createdAt: new Date("2022-02-22 13:06:33"),
        // updatedAt: new Date("2022-07-23 23:09:21"),
      },
      {
        events_id: 6,
        performers_id: 1,
        status: "reject",
        // createdAt: new Date("2022-08-23 16:46:51"),
        // updatedAt: new Date("2022-12-03 08:55:52"),
      },
      {
        events_id: 6,
        performers_id: 2,
        status: "accept",
        // createdAt: new Date("2022-12-28 22:00:23"),
        // updatedAt: new Date("2022-08-11 19:18:51"),
      },
      {
        events_id: 7,
        performers_id: 1,
        status: "pending",
        // createdAt: new Date("2022-05-27 04:55:48"),
        // updatedAt: new Date("2022-10-05 05:48:01"),
      },
      {
        events_id: 8,
        performers_id: 1,
        status: "pending",
        // createdAt: new Date("2022-05-17 05:54:54"),
        // updatedAt: new Date("2022-08-17 12:24:08"),
      },
    ],
  })

  /////////////////////////// EventsHashtag (1000 -- aline with event's qty) starts /////////////////////////

  await prisma.eventsHashtag.createMany({
    data: [
      {
        events_id: 1,
        hashtag_details_id: 27,
      },
      {
        events_id: 2,
        hashtag_details_id: 29,
      },
      {
        events_id: 3,
        hashtag_details_id: 26,
      },
      {
        events_id: 4,
        hashtag_details_id: 27,
      },
      {
        events_id: 5,
        hashtag_details_id: 28,
      },
      {
        events_id: 6,
        hashtag_details_id: 31,
      },
      {
        events_id: 7,
        hashtag_details_id: 26,
      },
      {
        events_id: 8,
        hashtag_details_id: 34,
      },
      {
        events_id: 9,
        hashtag_details_id: 30,
      },
      {
        events_id: 10,
        hashtag_details_id: 30,
      },
      {
        events_id: 11,
        hashtag_details_id: 26,
      },
      {
        events_id: 12,
        hashtag_details_id: 30,
      },
      {
        events_id: 13,
        hashtag_details_id: 30,
      },
      {
        events_id: 14,
        hashtag_details_id: 34,
      },
      {
        events_id: 15,
        hashtag_details_id: 29,
      },
      {
        events_id: 16,
        hashtag_details_id: 32,
      },
      {
        events_id: 17,
        hashtag_details_id: 27,
      },
      {
        events_id: 18,
        hashtag_details_id: 26,
      },
      {
        events_id: 19,
        hashtag_details_id: 30,
      },
      {
        events_id: 20,
        hashtag_details_id: 32,
      },
      {
        events_id: 21,
        hashtag_details_id: 35,
      },
      {
        events_id: 22,
        hashtag_details_id: 28,
      },
      {
        events_id: 23,
        hashtag_details_id: 25,
      },
      {
        events_id: 24,
        hashtag_details_id: 34,
      },
      {
        events_id: 25,
        hashtag_details_id: 32,
      },
    ],
  })

  ///////////////////////////////////////////visits_client_1 (1000/2000/5000) starts///////////////////////////////////////

  await prisma.visits.createMany({
    data: [
      {
        user_uuid: userUuid[0].uuid,
        device: "phone",
        ip_address: "192.0.2.1",
      },
      { user_uuid: userUuid[3].uuid, device: "web", ip_address: "192.0.2.5" },
    ],
  })

  //////////////////////////////////user_like_client_to_performer (250)  starts ///////////////////////////////////

  await prisma.userLike.createMany({
    data: [
      {
        subject_uuid: userUuid[0].uuid,
        target_uuid: userUuid[0].uuid,
      },
    ],
  })

  ///////////////////////// /review (400) starts ///////////////////////////
  await prisma.review.createMany({
    data: [
      {
        events_id: 1,
        users_id: 1,
        comments_content: "Good show",
        score: 4,
      },
    ],
  })
}
// async function main() {}
////start here ken

main().then(async () => {
  await prisma.$disconnect()
})
